((nil . ((indent-tabs-mode . nil)
         (fill-column . 79)))
 (c-mode . ((c-file-style . "gnu")))
 (c++-mode . ((c-file-style . "gnu")))
 (makefile-mode . ((indent-tabs-mode . t)))
 (octave-mode . ((octave-block-offset . 4))))
