#!/bin/sh

rm -rf example1
rm  -rf +example1
rm -f example1.log

rm -rf simulation-files1

rm -rf example2
rm  -rf +example2
rm -f example2.log

rm -rf simulation-files2

rm -f *.mat
rm -f *.m
rm -f *.dat
